//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimerchikRPM2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonent
    {
        public int Id { get; set; }
        public string Fio { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Age { get; set; }
        public string Inn { get; set; }
        public string Phone { get; set; }
        public byte[] Photo { get; set; }
    }
}
